spring:
  devtools:
    restart:
      enabled: true
  ##스웨거 접속 정보
  ## http://localhost:8080/swagger-ui/index.html
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

## My SQL
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://localhost:3306/vuerly?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    username: root
#    password: 1234
    url: jdbc:log4jdbc:mysql://192.168.0.141:3306/VUERLY?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: M2MNEW
    password: m2makstp
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      connection-init-sql: SELECT 1
      validation-timeout: 5000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

## mybatis
mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true


## 전체 로그 레벨 설정
logging:
  level:
    root: info

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

## 휴대폰 인증 value
phone:
  apiKey: NCSWLIJKYAF0ENST
  apiSecret: ZUVAIVYP7M6BQCAQPY4OBWP1STWHA0BT
